name: C/C++ CI

on:
  push:
    branches: [ Caribou-MK3 ]
  pull_request:
    branches: [ Caribou-MK3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y wget zip gawk python3
          sudo ln -sf /usr/bin/python3.8 /usr/bin/python
      - name: build variant BMH
        run: ./PF-build.sh -v Caribou320-MK3S-BMH.h -l EN_ONLY -d GOLD
      - name: build variant BEH
        run: ./PF-build.sh -v Caribou320-MK3S-BEH.h -l EN_ONLY -d GOLD
      - name: Upload hexfiles
        uses: actions/upload-artifact@v2
        with:
          name: CompiledFW
          path: /home/runner/work/Caribou-Firmware/PF-build-hex/
