name: C/C++ CI

on:
  push:
    branches: [ Caribou-MK3 ]
  pull_request:
    branches: [ Caribou-MK3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y wget zip gawk python3
          sudo ln -sf /usr/bin/python3.8 /usr/bin/python
