name: C/C++ CI

on:
  push:
    branches: [ Caribou-MK3 ]
  pull_request:
    branches: [ Caribou-MK3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install deps
    - run: |
        apt-get update
        apt-get -y install zip python3 wget gawk
    
    - name: build
      run: ./build.sh
